ZinOS/Controllers/DevelopersController.cs
using System.Web;
using System.Web.Mvc;
using ZinOS.Services.Definitions;
using ZinOS.Mvc;

namespace ZinOS.Controllers
{
    public class DevelopersController : ZinOSController
    {
        private readonly IZinOSAppService _zinOsAppService;

        public DevelopersController(IZinOSAppService zinOSAppService)
        {
            _zinOsAppService = zinOSAppService;
        }

        [HttpGet]
        public ActionResult Index()
        {
            return RedirectToAction("MyApps");
        }

        public ActionResult QuickStart()
        {
            return View();
        }

        //
        // GET: /Developers/MyApps
        [HttpGet]
        public ActionResult MyApps()
        {
            var apps = _zinOsAppService.GetAllAppsByUserId(CurrentUserId);

            ViewData.Model = new ViewModels.Developers.MyApps
                                 {
                                     UserApps = apps
                                 };

            return View();
        }

        //
        // GET: /Developers/SubmitApp
        [HttpGet]
        public ActionResult SubmitApp()
        {
            return View();
        }

        // POST: /Developers/SubmitApp
        [HttpPost]
        public ActionResult SubmitApp(HttpPostedFileBase zinOSAppZipFile)
        {
            try
            {
                _zinOsAppService.Submit(CurrentUserId, zinOSAppZipFile.InputStream);
            }
            catch (ValidationException validation)
            {
                foreach (var error in validation.Errors)
                    ModelState.AddModelError(error.ErrorKey, error.ErrorMessage);
            }

            if (ModelState.IsValid)
                return RedirectToAction("AppSubmited");

            return View();
        }

        //
        // GET: /Developers/AppSubmited
        [HttpGet]
        public ActionResult AppSubmited()
        {
            return View();
        }

        //
        // GET: /Developers/UpdateApp
        [HttpGet]
        public ActionResult UpdateApp(int appId)
        {
            var app = _zinOsAppService.GetApp(appId);
            ViewData.Model = app;
            return View();
        }


        // POST: /Developers/UpdateApp
        [HttpPost]
        public ActionResult UpdateApp(int zinOSAppId, HttpPostedFileBase zinOSAppZipFile)
        {
            try
            {
                _zinOsAppService.Update(CurrentUserId, zinOSAppId, zinOSAppZipFile.InputStream);
            }
            catch (ValidationException validationException)
            {
                foreach (var error in validationException.Errors)
                    ModelState.AddModelError(error.ErrorKey, error.ErrorMessage);
            }

            return ModelState.IsValid
                       ? (ActionResult) RedirectToAction("AppUpdated")
                       : View("UpdateApp", _zinOsAppService.GetApp(zinOSAppId));
        }

        [HttpGet]
        public ActionResult AppUpdated()
        {
            return View();
        }
    
    }
}

ZinOS/Controllers/UserController.cs
using System.Web.Mvc;
using ZinOS.Mvc;
using ZinOS.Services.Definitions;
using ZinOS.OAuth;
using ZinOS.Services.Definitions.Users;

namespace ZinOS.Controllers
{
    public class UserController : ZinOSController
    {
        private readonly IUserService _userService;
        private readonly IDropboxService _dropboxService;

        public UserController(IUserService userService, IDropboxService dropboxService)
        {
            _userService = userService;
            _dropboxService = dropboxService;
        }

        [HttpGet]
        [IgnoreAuthorization]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [IgnoreAuthorization]
        public ActionResult Create(ViewModels.User.Create userCreateModel)
        {
            if (!ModelState.IsValid)
                return View();

            try
            {
                var newUser = userCreateModel.GetUser();
                _userService.CreateUser(newUser);
            }
            catch (ValidationException validationException)
            {
                foreach (var error in validationException.Errors)
                    ModelState.AddModelError(error.ErrorKey, error.ErrorMessage);
            }

            if (ModelState.IsValid)
                return RedirectToAction("UserCreated");

            return View();
        }

        [HttpGet]
        [IgnoreAuthorization]
        public ActionResult UserCreated()
        {
            return View();
        }

        [HttpGet]
        public ActionResult UserEdited()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Edit()
        {
            var user = _userService.GetUserById(CurrentUserId);
            return View(user);
        }

        [HttpPost]
        public ActionResult Edit(ViewModels.User.Edit userEditModel)
        {
            if (!ModelState.IsValid)
            {
                var user = _userService.GetUserById(CurrentUserId);
                return View(user);
            }

            try
            {
                _userService.ChangeUserPassword(CurrentUserId,userEditModel.Password);
            }
            catch (ValidationException validationException)
            {
                foreach (var error in validationException.Errors)
                    ModelState.AddModelError(error.ErrorKey, error.ErrorMessage);
            }

            if (ModelState.IsValid)
                return RedirectToAction("UserEdited");

            return View(_userService.GetUserById(CurrentUserId));
        }

        [HttpGet]
        public ActionResult AuthenticateDropbox()
        {
            var consumer = new DropboxOAuthConsumer(CurrentUserId, _dropboxService, _userService);

            if (consumer.IsAuthorized())
                return RedirectToAction("Edit");

            consumer.RequestToken();

            return null;
        }
    }
}

ZinOS/Views/Shared/LoginControl.cshtml
<div class="login-control" id="login-control">
    @if (ViewBag.UserIsAuthenticated != null && ViewBag.UserIsAuthenticated)
    {
        <div class="button logout-button">logout</div>
    }
    else
    {
        <div class="label">username</div>
        <input type="text" />
        <div class="label">password</div>
        <input type="password" />
        <div class="button login-button">login</div>
    }
</div>

ZinOS/Views/Shared/_Layout.cshtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
    <head>
        <title>@ViewBag.Title</title>
        <link href="@Url.Content("~/Content/Shared/_Layout/default.css")" rel="stylesheet" type="text/css" />

        <script src="@Url.Content("~/Scripts/jquery-1.4.4.min.js")" type="text/javascript"></script>
        <script src="@Url.Content("~/Content/Shared/ZinOS/zinos.core.js")" type="text/javascript"></script>
        
        <link href="@Url.Content("~/Content/Shared/LoginControl/css/login-control.css")" rel="stylesheet" type="text/css" />
        <script src="@Url.Content("~/Content/Shared/LoginControl/js/login-control.js")" type="text/javascript"></script>
        @RenderSection("HeaderContent", required: false)         
    </head>
    <body>
    
        <div id="main">
            <div id="header">    
                <h1>ZinOS</h1>
                @{
                    Html.RenderPartial("LoginControl");
                }
            </div>
            <div id="content">
                @RenderBody()
            </div>
            <div id="footer">
                <div class="menu">
                    <div class="title">Developers</div>
                    <div class="item">@Html.ActionLink("My Apps", "MyApps", "Developers")</div>
                    <div class="item">@Html.ActionLink("Submit an App", "SubmitApp", "Developers")</div>
                    <div class="item">@Html.ActionLink("Quick start", "QuickStart", "Developers")</div>
                </div>
                <div class="menu">
                    <div class="title">ZinOS</div>
                    <div class="item">@Html.ActionLink("Home", "Index", "Home")</div>
                </div>
                <div class="menu">
                    <div class="title">User</div>
                    <div class="item">@Html.ActionLink("My Account", "Edit", "User")</div>
                    <div class="item">@Html.ActionLink("Create Account", "Create", "User")</div>
                </div>
            </div>
        </div>
    </body>
</html>